Update sysinfo

diff --git a/sysinfo b/sysinfo
--- a/sysinfo
+++ b/sysinfo
@@ -16,7 +16,7 @@ if [[ $# -eq 1 && ( $1 == "-h" || $1 == "--help" ) ]]; then
 # if argument something else, see if its an app
 elif [[ $# -eq 1 ]]; then
     # check the app with various package managers
-    appvalue="$(rpm -qa | grep $1 || dpkg-query -W $1 || pacman -Qi $1 || pamac info $1 || emerge --search $1 || apk info $1 || nix-env -q | grep $1 || yay -Si $1 || snap info $1 || flatpak search $1)"
+    appvalue="$(rpm -qa | grep $1 || dpkg-query -W $1 || pacman -Qi $1 || pamac info $1 || emerge --search $1 || apk info $1 || nix-env -q | grep $1 || yay -Si $1 || snap info $1 || flatpak list | grep $1 || flatpak search $1)"
     # if appvalue not existent, app not found. Maybe an exotic package manager is missing, feel free to add it!
     if [ -z "$appvalue" ]; then
       echo "Program not found"
@@ -58,17 +58,48 @@ GPUinfo="GPU: $(glxinfo | grep -Ei 'device|memory' | head -2 | sed -e 's/Device:
 
 
 
+# ---------------------- Audio Information, Pipewire or Pulseaudio --------------
+
+# Check if user has JACK installed
+if command -v jackd >/dev/null 2>&1; then
+    AudioInfo="Audio: Jack"
+
+# else check if user uses Alsa
+else
+    if command -v alsamixer >/dev/null 2>&1; then
+        AudioInfo="Audio: Alsa"
+    fi
+fi
+
+# if Jack is used, check if it is the soundserver
+if [[ $AudioInfo == "Jack" ]]; then
+    if command -v alsamixer >/dev/null 2>&1; then
+        AudioInfo += ", Alsa"
+    fi
+fi
+
+# Check if user has pipewire installed
+if command -v "pipewire -h" >/dev/null 2>&1; then
+    AudioInfo += ", Pipewire"
+fi
+
+# Check if user has pulseaudio installed
+if command -v pulseaudio >/dev/null 2>&1; then
+    AudioInfo += ", Pulseaudio"
+fi
+
+
 # ----- OUTPUT AND CLIPBOARD COPY ------
 
 #Visual printing:
-printf "$appvalue${BLUE}${BOLD}--- Software --- ${RESET} \n$OSinfo \n$Plasmainfo \n$FWinfo \n$Qtinfo \n$Kernelinfo \n$Compositorinfo \n \n${BLUE}${BOLD}--- Hardware ---${RESET} \n$CPUinfo \n$RAMinfo \n$GPUinfo \n \n"
+printf "$appvalue${BLUE}${BOLD}--- Software --- ${RESET} \n$OSinfo \n$Plasmainfo \n$FWinfo \n$Qtinfo \n$Kernelinfo \n$Compositorinfo \n \n${BLUE}${BOLD}--- Hardware ---${RESET} \n$CPUinfo \n$RAMinfo \n$GPUinfo \n$AudioInfo \n \n"
 
 
 # Clipboard
 while true; do
     read -p "Copy to clipboard? (y/n) > " yn
     case $yn in
-        [Yy]* ) echo -e "$appvalue--- Software ---\n$OSinfo\n$Plasmainfo\n$FWinfo\n$Qtinfo\n$Kernelinfo\n$Compositorinfo\n\n--- Hardware ---\n$CPUinfo\n$RAMinfo\n$GPUinfo"| tee >(wl-copy || xclip -selection clipboard || xsel -ib) >/dev/null && echo -e "\n🗒️ Copied to clipboard!"|| echo "Clipboard command not found. Install wl-clipboard for Wayland or xsel or xclip for X11." && break;;
+        [Yy]* ) echo -e "$appvalue--- Software ---\n$OSinfo\n$Plasmainfo\n$FWinfo\n$Qtinfo\n$Kernelinfo\n$Compositorinfo\n\n--- Hardware ---\n$CPUinfo\n$RAMinfo\n$GPUinfo\n$AudioInfo"| tee >(wl-copy || xclip -selection clipboard || xsel -ib) >/dev/null && echo -e "\n🗒️ Copied to clipboard!"|| echo "Clipboard command not found. Install wl-clipboard for Wayland or xsel or xclip for X11." && break;;
         [Nn]* ) break;;
         * ) echo "Please answer yes or no.";;
     esac
